### ISSUE TITLE
Preprocessing GloVe vectors

### ISSUE THREAD

**Issue by YixingLuan** [malllabiisc/EWISE#5]
Hello, 
Thank you for the interesting work.

Now, I'm trying to use your system with the provided pre-trained models. 
However, running "create_glove_dict.py" in "preprocess.sh" takes a very long time.
I tried it in several machines, but it gets an OOM error in some machines and it doesn't terminate over 3 days in other machines. 

Is it possible for you to provide preprocessed GloVe vectors so that I can directly use the provided pre-trained models to perform WSD evaluations? 
Or, could you tell me how I can overcome this issue? 

Thank you.

**Comment by SawanKumar28** [comment]
It's just making a dictionary using the word embeddings file. The output is around 5GB. So, you can try running on a machine which can handle that.

Otherwise, the output of this script is used as argument 1 of  "initialize_word_embeddings.py" - the embeddings are fetched through the "model" variable (line 10). You can directly read the embeddings of the words in this file, rather than saving them into a dictionary first in "create_glove_dict.py".

**Comment by YixingLuan** [comment]
Thank you for your quick advice. 

Since my machines couldn't handle it properly, I split the GloVe file and recursively stored them into 1 dictionary by changing "create_glove_dict.py" for a bit. 
Now, I could successfully finish the preprocessing and run the pre-trained model. 
Also, I could confirm that I get the same performance with you (ALL=72.1% F1).

I'm closing this issue.
